sudo usermod -aG docker $USER

FROM python:3.9

WORKDIR /app/backend

COPY requirements.txt /app/backend
RUN pip install -r requirements.txt

COPY . /app/backend

EXPOSE 8000

CMD python /app/backend/manage.py runserver 0.0.0.0:8000


docker run -d -p 8000:8000 django-app:latest

curl -L http://127.0.0.1:8000